### PR TITLE
Update syncNode

### PR DESCRIPTION
**Pull request by lewisakura**
Change from old URL to new URL

### CODE REVIEW

**Comment by dmarcuse** [comment]
First of all, you need the protocol - "http://". Secondly, the URLs are functionally identical, so there is no need to change it.

**Comment by lewisakura** [comment]
There is no 'http://' on links that have a sub-domain. I'll add it anyway though.

**Comment by dmarcuse** [comment]
Yes, there is. Otherwise you have not specified the protocol (http vs https) which is necessary to connect. Not sure where you came up with that.

Proof:
Image

Note that the first call does not return anything, indicating a failed connection. This was tested in CCEmuRedux with CC 1.74 and thus should hold true to CC and other emulators.

**Comment by BTCTaras** [comment]
This file is no longer used; changing it wouldn't do anything.

**Comment by dmarcuse** [comment]
So much for "no longer used"

**Comment by BTCTaras** [comment]
The legacy installer still uses it - this merge actually broke it until I fixed it again

**Comment by dmarcuse** [comment]
What about miners and external wallets? Those still need this too.

**Comment by LewisTehMinerz** [comment]
"this merge actually broke it until I fixed it again"

You didn't change anything on the file. I just compared my pull request and the file change. There is nothing different about the files.

**Pull request merged**
